### PR TITLE
Make dependencies explicit

### PR DESCRIPTION
**Pull request by menelaos**

### CODE REVIEW

**Comment by garyb** [comment]
What's the advantage of doing this?

**Comment by menelaos** [comment]
Isn't it considered good practice to list dependencies explicitly? I just thought that if Haskell/Cabal even enforces this and does not allow `hidden packages`, it might be a good thing to do.

**Comment by menelaos** [comment]
Here! Proof! :-)
http://ircbrowse.net/browse/purescript?id=276085&timestamp=1456866936#t1456866936
Just kidding, if it's not relevant, feel free to just close this.

**Comment by garyb** [comment]
I think when we eventually move away from bower we'd like the listing to be explicit, to enable private dependencies and things like that, but I think for the mean time transitive dependencies are fine in bower.

The only disadvantage of listing everythng now is there maybe be a bit more bumping of versions required if everything is listed explicitly, but then again if everything uses `^` ranges then that can also be avoided. Basically, I'm indifferent about it right now :laughing:.

**Comment by menelaos** [comment]
Closing this PR as it is now outdated anyway.

**Pull request closed without merging**
