### PR TITLE
Update to v0.14.0-rc3

### PR DESCRIPTION
**Pull request by JordanMartinez**
- Update travis, dependencies and purescript-psa
- Fix missing kind declaration error

Backlinking to purescript/purescript#3942

### CODE REVIEW

**Comment by JordanMartinez** [comment]
Huh... Build fails due to `purescript-newtype` not installing right: https://travis-ci.org/github/purescript/purescript-foldable-traversable/builds/734828638#L550

**Comment by hdgarrood** [comment]
My guess would be that this is because one of the dependencies hasn't been updated yet, and so it has a dependency on a tagged version of `newtype` rather than depending on `master`.

**Comment by JordanMartinez** [comment]
Ah... You're right. I haven't updated `orders` yet. Here's all of its dependencies:
```
["bifunctors","control","invariant","maybe","newtype","orders","prelude"]
```

**Comment by JordanMartinez** [comment]
CI now builds. Can I get an approval?

**Review by hdgarrood — APPROVED** [review]

**Pull request merged**
