### PR TITLE
Wrap `traverseArrayImpl` IIFE in parentheses

### PR DESCRIPTION
**Pull request by tslawler**

### CODE REVIEW

**Comment by hdgarrood** [comment]
Just wondering, since it's not clear to me - what do we gain by doing this?

**Comment by LiamGoodacre** [comment]
👍 The gain here is in readibility by conforming to a very common syntactic pattern.  This is of increasing aid the longer a function's implementation is as it can be easy to miss the `()` on the very last line.

**Comment by hdgarrood** [comment]
Right, makes sense, thanks. I think we should hold off merging until #48 is resolved though.

**Comment by hdgarrood** [comment]
Thanks!

**Pull request merged**
