### PR TITLE
Let findWithIndex also return index of found value

### PR DESCRIPTION
**Pull request by mbid**
Yeah, I've screwed up slightly in the previous PR: haskell's `findWithIndex` also returns the index of the found value, and I forgot to do it here. This should fix it.

Because Data.Tuple depends on this package, `findWithIndex` can't return
an actual `Tuple`. `ValueWithIndex` exists as a workaround.

Also tweaks the test slightly, and adds a type signature for a local
function.

### CODE REVIEW

**Comment by hdgarrood** [comment]
Looks good but I'm not sure the type synonym is adding much.

**Comment by mbid** [comment]
Is this better?

**Comment by hdgarrood** [comment]
Yes, thanks - just one thing: bit of a nit but I think it's best to have a consistent number of spaces either side of a set of curly braces.

**Comment by mbid** [comment]
Ah, good thing you caught that.

**Comment by paf31** [comment]
Looks good, but obviously it's a breaking change.

**Pull request merged**
