### PR TITLE
Add Foldable1

### PR DESCRIPTION
**Pull request by puffnfresh**
For when you only need an Apply or Semigroup instead of Applicative or
Monoid.

### CODE REVIEW

**Comment by puffnfresh** [comment]
I have a feeling this might be better formulated in terms of foldl1 and foldr1. What do you think?

**Comment by puffnfresh** [comment]
I think foldr1 should be derivable using Dual, is that right?

**Comment by paf31** [comment]
Looks nice, thanks! 

Could you please add some comments? I'm trying to require code comments on all exported core library functions and types now that we have public docs. `Act` in particular could benefit from a few explanatory comments IMO, since `f a` has at least a couple of sensible `Semigroup` instances.

And yes, I think `Dual` is a nice way to derive `foldr`, rather than requiring both in instances.

**Comment by paf31** [comment]
@joneshf may like to weigh in on the `foldr` stuff too?

**Comment by garyb** [comment]
If you get a chance could you rebase and update this? It still looks good to me :+1:

**Comment by LiamGoodacre** [comment]
We should probably start a naming convention for default/derived functions?
With my PR https://github.com/purescript/purescript-foldable-traversable/pull/30 I've used `_Default` whereas you have used `derived_`.

**Comment by garyb** [comment]
Yeah, that would be good. I have no particular preference for either option though.

**Comment by LiamGoodacre** [comment]
Is this PR dead? @puffnfresh

**Comment by sharkdp** [comment]
I'd also be really interested in this.. I would also help by sending an updated PR.

**Comment by paf31** [comment]
This PR seems to be dead, so I'll close it for now, but we can reopen it if the issues above can be addressed. Thanks!

**Pull request closed without merging**
