### PR TITLE
Remove Ref instance

### PR DESCRIPTION
**Pull request by garyb**
For release as `v0.2.0`

### CODE REVIEW

**Comment by garyb** [comment]
We talked about this on IRC at the time, but for future reference if we look back at this post - changing the dependencies to what I proposed above was abandoned as it doesn't really work out.

**Comment by garyb** [comment]
Alright, it turns out my last script was only pulling back the first page of repos for the orgs, so it was a little incomplete. Here's the revised list:

```
purescript-angular
purescript-arb-instances
purescript-argonaut
purescript-bifunctors
purescript-channels
purescript-const
purescript-coproducts
purescript-distributive
purescript-drawing
purescript-foreign
purescript-free
purescript-generics
purescript-graphs
purescript-handlebars
purescript-identity
purescript-inject
purescript-jquery
purescript-lazy
purescript-lens
purescript-lists
purescript-machines
purescript-maps
purescript-mongodbf
purescript-node-fs
purescript-parsing
purescript-pattern-arrows
purescript-quickcheck
purescript-sammy
purescript-sets
purescript-streams
purescript-string-parsers
purescript-strongcheck
purescript-task
purescript-transformers
purescript-yaml
purescript-yargs
purescript-yoneda
```

**Comment by garyb** [comment]
A slightly more helpful formulation:

```
purescript-angular
    purescript-arrays
    purescript-either
    purescript-exceptions
    purescript-foldable-traversable
    purescript-maybe
    purescript-simple-dom
    purescript-transformers
    purescript-tuples
purescript-arb-instances
    purescript-control
    purescript-either
    purescript-maybe
    purescript-monoid
    purescript-quickcheck
    purescript-tuples
purescript-argonaut
    purescript-control
    purescript-either
    purescript-foldable-traversable
    purescript-globals
    purescript-lens
    purescript-maps
    purescript-maybe
    purescript-sets
    purescript-strings
    purescript-tuples
purescript-bifunctors
    purescript-const
    purescript-control
    purescript-either
    purescript-foldable-traversable
    purescript-monoid
    purescript-tuples
purescript-channels
    purescript-arrays
    purescript-arrows
    purescript-foldable-traversable
    purescript-lazy
    purescript-maybe
    purescript-monoid
    purescript-profunctor
    purescript-transformers
    purescript-tuples
purescript-const
    purescript-contravariant
    purescript-foldable-traversable
    purescript-monoid
purescript-coproducts
    purescript-either
    purescript-foldable-traversable
purescript-distributive
    purescript-identity
purescript-drawing
    purescript-arrays
    purescript-canvas
    purescript-control
    purescript-either
    purescript-foldable-traversable
    purescript-generics
    purescript-math
    purescript-maybe
    purescript-monoid
    purescript-random
    purescript-tuples
purescript-foreign
    purescript-arrays
    purescript-either
    purescript-foldable-traversable
    purescript-maybe
    purescript-tuples
purescript-free
    purescript-control
    purescript-coproducts
    purescript-either
    purescript-exists
    purescript-foldable-traversable
    purescript-inject
    purescript-lazy
    purescript-transformers
purescript-generics
    purescript-arrays
    purescript-either
    purescript-foldable-traversable
    purescript-maybe
    purescript-strings
    purescript-tuples
purescript-graphs
    purescript-arrays
    purescript-foldable-traversable
    purescript-maps
    purescript-maybe
    purescript-sets
purescript-handlebars
    handlebars
    purescript-jquery
purescript-identity
    purescript-foldable-traversable
purescript-inject
    purescript-coproducts
    purescript-either
    purescript-maybe
purescript-jquery
    purescript-dom
    purescript-foreign
purescript-lazy
    purescript-arrays
    purescript-control
    purescript-foldable-traversable
    purescript-monoid
purescript-lens
    purescript-const
    purescript-distributive
    purescript-either
    purescript-identity
    purescript-maybe
    purescript-profunctor
purescript-lists
    purescript-arrays
    purescript-foldable-traversable
    purescript-lazy
    purescript-maybe
    purescript-monoid
    purescript-strings
    purescript-transformers
    purescript-tuples
    purescript-unfoldable
purescript-machines
    purescript-arrays
    purescript-arrows
    purescript-foldable-traversable
    purescript-maybe
    purescript-monoid
    purescript-profunctor
    purescript-tuples
purescript-maps
    purescript-arrays
    purescript-foldable-traversable
    purescript-math
    purescript-maybe
    purescript-strings
    purescript-tuples
purescript-mongodbf
    purescript-foreign
    purescript-free
purescript-node-fs
    purescript-datetime
    purescript-either
    purescript-exceptions
    purescript-foreign
    purescript-maybe
    purescript-node-buffer
    purescript-node-path
purescript-parsing
    purescript-arrays
    purescript-either
    purescript-foldable-traversable
    purescript-identity
    purescript-maybe
    purescript-strings
    purescript-transformers
purescript-pattern-arrows
    purescript-arrays
    purescript-arrows
    purescript-control
    purescript-foldable-traversable
    purescript-maybe
    purescript-transformers
    purescript-tuples
purescript-quickcheck
    purescript-arrays
    purescript-either
    purescript-exceptions
    purescript-foldable-traversable
    purescript-math
    purescript-maybe
    purescript-random
    purescript-strings
    purescript-tuples
purescript-sammy
    purescript-jquery
    sammy
purescript-sets
    purescript-arrays
    purescript-foldable-traversable
    purescript-maps
    purescript-maybe
    purescript-tuples
purescript-streams
    purescript-monoid
    purescript-task
    purescript-trampoline
    purescript-tuples
purescript-string-parsers
    purescript-arrays
    purescript-control
    purescript-foldable-traversable
    purescript-maybe
    purescript-strings
purescript-strongcheck
    purescript-arrays
    purescript-either
    purescript-enums
    purescript-exceptions
    purescript-foldable-traversable
    purescript-free
    purescript-lazy
    purescript-lists
    purescript-machines
    purescript-math
    purescript-maybe
    purescript-random
    purescript-strings
    purescript-transformers
    purescript-tuples
purescript-task
    purescript-transformers
    purescript-tuples
purescript-transformers
    purescript-arrays
    purescript-control
    purescript-either
    purescript-identity
    purescript-monoid
    purescript-tuples
purescript-yaml
    js-yaml
    purescript-either
    purescript-foreign
purescript-yargs
    purescript-easy-ffi
    purescript-either
    purescript-exceptions
    purescript-foreign
purescript-yoneda
    purescript-control
    purescript-exists
    purescript-transformers
```

The indented stuff are the things that each module depends on that also appear in the list, so for example, we can see that `purescript-mongodbf` shouldn't be released/bumped until `purescript-foreign` and `purescript-free` have also been done.

**Comment by garyb** [comment]
Alright, I've re-released or submitted PRs for almost everything now aside from:

- `purescript-argonaut`, as this needs a new release of `purescript-lens` which I did as PR
- `purescript-strongcheck`, as this needs a new release of `purescript-machines`, PR again
- `purescript-streams` and `purescript-task`, as these things are hanging around in contrib unfinished (I think?) and nobody apart from @puffnfresh seems to know anything about them!
- `purescript-yaml` not sure what the deal with this one is it seems we have a fork in contrib as well as @Fresheyeball's own version still being out there.

**Comment by puffnfresh** [comment]
@garyb purescript-streams and purescript-task are not complete. Someone has hopefully come up with a sensible trampolining solution since, so that task is made redundant.

**Pull request merged**
