### PR TITLE
Docs

### PR DESCRIPTION
**Pull request by paf31**
@garyb Could you please review this? Thanks.

### CODE REVIEW

**Comment by garyb** [comment]
Looks good to me. Just two things: `foldrArray` and `foldlArray` are left undocumented, and I don't know if we want to go ahead and make that change to use `Semiring` for `sum` and `Ring` for `product` now. But :+1:

**Comment by paf31** [comment]
Huh, I guess I assumed `foldlArray` and `foldrArray` were internal. Any idea why they're exported?

I was thinking we could add docs in a separate commit, since `sum` and `product` changes will be breaking.

**Comment by garyb** [comment]
I don't know why they're exported directly actually, no, as obviously the instance makes them accessible already.

Good point on the `Num` stuff.

**Comment by paf31** [comment]
Ok, I'll merge this then, and we can delete the exports as part of the next breaking change.

Time to break out the old dependency graph tool I guess :cry:

**Comment by garyb** [comment]
Ouch... yeah. And it is indeed a breaking change, there are a few people importing the specialised folds directly according to code search.

**Pull request merged**
