### PR TITLE
Add `findMap`

### PR DESCRIPTION
**Pull request by LiamGoodacre**

### CODE REVIEW

**Comment by paf31** [comment]
Looks great, I often want this function.

However, I think it would be nice to think about how to implement functions like this without having to traverse a whole structure in general, when the predicate is satisfied near the start. Strictness bites us here for large input structures.

**Comment by LiamGoodacre** [comment]
Agreed.

Might not be the best approach but I've spent the last hour or so playing with hacking a `NonStrict` constraint in various places to try and get things to 'just work'.  The nicest configuration I came up with was to have semigroup defined slightly differently:

```purescript
class NonStrict
instance nonStrict :: NonStrict
class Semigroup m where
  append :: m -> (NonStrict => m) -> m
```

Because the constraint is actually adding another hidden argument, the rhs won't get evaluated until the append actually uses it.

I couldn't think of a nice way to do it otherwise - if you have any ideas I'd love to hear them? 😄

**Comment by paf31** [comment]
Clever!

**Comment by LiamGoodacre** [comment]
I also tried both:
```purescript
findMap :: forall t a b. Foldable t => (a -> (NonStrict => Maybe b)) -> f a -> Maybe b
findMap :: forall t a b. Foldable t => (a -> Maybe (NonStrict => b)) -> f a -> Maybe b
```
and then making a version of `First` with either `NonStrict` built-in or `Unit -> Maybe t` so it doesn't evaluate the rhs unless it needs it.  But I kept getting unification errors with the constraint in various places.

I'll keep trying for a bit and see where I get.

**Comment by LiamGoodacre** [comment]
Worked out a proper way of doing it without constraints: just make a lazy version of `First`.

```purescript
data FST b = FST (Unit -> Maybe b)

runFST :: forall t. FST t -> Maybe t
runFST (FST f) = f unit

instance semigroupFST :: Semigroup (FST b) where
  append (FST l) (FST r) = FST \a -> case l a of
    Nothing -> r a
    x -> x

instance monoidFST :: Monoid (FST b) where
  mempty = FST (\_ -> Nothing)

findMap :: forall f a b. Foldable f => (a -> Maybe b) -> f a -> Maybe b
findMap p xs = runFST (foldMap go xs) where
  go x = FST (\_ -> p x)
```

**Comment by LiamGoodacre** [comment]
Hmm this actually doesn't do the right thing.  It does prevent evaulating `p` on things it doesn't need to, but it'll still traverse the whole data structure. 😒

**Comment by garyb** [comment]
@paf31 shall we merge this as it is and then find a better performing version later?

**Comment by paf31** [comment]
Yep, sounds good.

**Pull request merged**
